### PR TITLE
-add crown/bank balance to monitor info endpoint

### PR DESCRIPTION
**Pull request by djpnewton**
@eoliveros can you test this change with grafana/kapacitor

### CODE REVIEW

**Review by eoliveros — COMMENTED** [review]
it works but there is a lot of:
```
[crown_financial INFO] :: calling balance..
[crown_financial INFO]    GET - https://api.mycrown.services/balance
[crown_financial INFO] :: calling balance..
[crown_financial INFO]    GET - https://api.mycrown.services/balance
[crown_financial INFO] :: calling balance..
[crown_financial INFO]    GET - https://api.mycrown.services/balance
[crown_financial INFO] :: calling balance..
[crown_financial INFO]    GET - https://api.mycrown.services/balance
[crown_financial INFO] :: calling balance..
[crown_financial INFO]    GET - https://api.mycrown.services/balance
```

**Comment by djpnewton** [comment]
> it works but there is a lot of:
> 
> ```
> [crown_financial INFO] :: calling balance..
> [crown_financial INFO]    GET - https://api.mycrown.services/balance
> [crown_financial INFO] :: calling balance..
> [crown_financial INFO]    GET - https://api.mycrown.services/balance
> [crown_financial INFO] :: calling balance..
> [crown_financial INFO]    GET - https://api.mycrown.services/balance
> [crown_financial INFO] :: calling balance..
> [crown_financial INFO]    GET - https://api.mycrown.services/balance
> [crown_financial INFO] :: calling balance..
> [crown_financial INFO]    GET - https://api.mycrown.services/balance
> ```

is that not fixed by https://github.com/zap-me/beryllium/pull/96?

**Comment by eoliveros** [comment]
> > it works but there is a lot of:
> > ```
> > [crown_financial INFO] :: calling balance..
> > [crown_financial INFO]    GET - https://api.mycrown.services/balance
> > [crown_financial INFO] :: calling balance..
> > [crown_financial INFO]    GET - https://api.mycrown.services/balance
> > [crown_financial INFO] :: calling balance..
> > [crown_financial INFO]    GET - https://api.mycrown.services/balance
> > [crown_financial INFO] :: calling balance..
> > [crown_financial INFO]    GET - https://api.mycrown.services/balance
> > [crown_financial INFO] :: calling balance..
> > [crown_financial INFO]    GET - https://api.mycrown.services/balance
> > ```
> 
> is that not fixed by #96?

the quietening of logs applied on #96 appears to affect dasset.py. as far as i can tell, #96 doesn't affect crown_finance.py

**Comment by djpnewton** [comment]
ok try now

**Comment by eoliveros** [comment]
still getting the following every 15seconds:
```
[crown_financial INFO]    GET - https://api.mycrown.services/balance
[crown_financial INFO]    GET - https://api.mycrown.services/balance
[crown_financial INFO]    GET - https://api.mycrown.services/balance
```

**Comment by djpnewton** [comment]
ah ok try now

**Comment by eoliveros** [comment]
no more extra logs from crown.

got the following in grafana:
image

had to adjust the dasset balances because of the change on monitor_endpoint.py and added the crown balance as well.

adjusted the tick script for dasset since renaming to exchange_{asset}_available and added a tick script for crown_balance with a threshold of 2k.

**Review by eoliveros — APPROVED** [review]
looks good.

**Pull request merged**
