### PR TITLE
convert capacity on channel from msat to sat.

### PR DESCRIPTION
**Pull request by eoliveros**
Fixing the issue with capacity on the individual channels from msat to sat.

### CODE REVIEW

**Comment by djpnewton** [comment]
why is lint failing?

**Comment by eoliveros** [comment]
> why is lint failing?

its failing on the api_endpoint. not entirely sure why since i didnt make any changes on the api_endpoint.

**Comment by djpnewton** [comment]
there is a new version of pyright, I will rerun the test

**Comment by djpnewton** [comment]
maybe try rebasing to master

**Comment by eoliveros** [comment]
> maybe try rebasing to master

did the following:
- git rebase master channel_capacity_fix
- git push -f

though i think it might be better to close this PR > git pull upstream master(from master local) > create/checkout the new branch > apply the one line change i did?

Will try that if it doesn't work.

**Comment by eoliveros** [comment]
after doing a git push -f seems like it worked... i can see the latest master change and then my change at the HEAD.

**Review by djpnewton — APPROVED** [review]

**Pull request merged**
