### PR TITLE
add fixed fee component

### PR DESCRIPTION
**Pull request by djpnewton**
-add fixed fee component
-mock more dasset stuff

### CODE REVIEW

**Comment by eoliveros** [comment]
before ordering:
image

ordering: $25

image
not sure what the "update" button does since it doesn't appear to do anything when clicked. When click on "accept"

image
checking on the "order history" and after a few minutes it changes to "COMPLETED" like the above image.

image
checking on the balances: it looks like the BTC balance is approximately $1+ less than what it should be, so its taking $1 + fees.
though it might be a coincidence but the value of sats is divisible by 10000 and you get the NZD value. hmmm...

This doesn't look correct.
image
The value of sats looks like for a $100(NZD) rather than $25(NZD)

**Comment by eoliveros** [comment]
converted $100(NZD) to USD and im getting the value of $61.69(USD)

So tried using coinmarketcap.com to get $61.69(USD) worth of BTC and getting the following(it looks like its change it $61.17):
image

**Comment by eoliveros** [comment]
also there is an issue with the balances:
image

against:
image


the NZD value is less than half of the USD value.

**Comment by djpnewton** [comment]
dont expect the prices to be accurate when we are mocking the exchange.

I just put in a fake price around 10000$ when mocking the exchange

**Review by 4855062503 — APPROVED** [review]
LGTM.

**Pull request merged**
