### PR TITLE
fix crash when jinja template parameters are not supplied for `payment_request.html`

### PR DESCRIPTION
**Pull request by djpnewton**

### CODE REVIEW

**Review by eoliveros — COMMENTED** [review]
Is there anyway to test this without using real money?

**Comment by djpnewton** [comment]
> Is there anyway to test this without using real money?

yeah just create a nzd deposit, you dont actually have to complete it, and/or set `WINDCAVE_MOCK=true`

**Comment by eoliveros** [comment]
created a $20 NZD deposit:
image


That seems to work.

**Review by eoliveros — APPROVED** [review]
seems to be able to create a deposit of $20NZD

**Pull request merged**
