### PR TITLE
backup lightning channel state

### PR DESCRIPTION
**Pull request by eoliveros**
- backup the sqlite3 file for lightningd to a folder in the host.

### CODE REVIEW

**Comment by djpnewton** [comment]
We dont need to replace the entire entrypoint script. entrypoint.sh starts lightningd like: `lightningd "$@"` so you could just override the entrypoint in our child Dockerfile and do something like:

```ENTRYPOINT [ "/usr/bin/tini", "-g", "--", "./entrypoint.sh", "--wallet", "<WALLET_PARAM>" ]```

**Comment by djpnewton** [comment]
even better add a file called `entrypoint-shim.sh` with the following data:

```
#!/usr/bin/env bash

networkdatadir="${LIGHTNINGD_DATA}/${LIGHTNINGD_NETWORK}"
wallet="sqlite3://$networkdatadir/lightningd.sqlite3"

if [ -n "LIGHTNINGD_REPLICA" ]; then
  wallet="$wallet:$LIGHTNINGD_REPLICA"
fi

entrypoint.sh --wallet "$wallet" "$@"
```

and add `ENTRYPOINT [ "/usr/bin/tini", "-g", "--", "./entrypoint-shim.sh"]` to our Dockerfile then we only need a single environment variable (`LIGHTNINGD_REPLICA`) and it is an optional simple file path

**Comment by eoliveros** [comment]
> We dont need to replace the entire entrypoint script. entrypoint.sh starts lightningd like: `lightningd "$@"` so you could just override the entrypoint in our child Dockerfile and do something like:
> 
> `ENTRYPOINT [ "/usr/bin/tini", "-g", "--", "./entrypoint.sh", "--wallet", "<WALLET_PARAM>" ]`

the entrypoint file didn't exists in our repo. its originally in the image.

**Comment by eoliveros** [comment]
> even better add a file called `entrypoint-shim.sh` with the following data:
> 
> ```
> #!/usr/bin/env bash
> 
> networkdatadir="${LIGHTNINGD_DATA}/${LIGHTNINGD_NETWORK}"
> wallet="sqlite3://$networkdatadir/lightningd.sqlite3"
> 
> if [ -n "LIGHTNINGD_REPLICA" ]; then
>   wallet="$wallet:$LIGHTNINGD_REPLICA"
> fi
> 
> entrypoint.sh --wallet "$wallet" "$@"
> ```
> 
> and add `ENTRYPOINT [ "/usr/bin/tini", "-g", "--", "./entrypoint-shim.sh"]` to our Dockerfile then we only need a single environment variable (`LIGHTNINGD_REPLICA`) and it is an optional simple file path

will make some changes to see if i could start the above.

**Comment by djpnewton** [comment]
I made some changes based on my comments that simplify setting up the replica.

all you need to do is put `LIGHTNINGD_REPLICA=1` into the env and it will then create `./lightningd/replica/lightningd.sqlite3`

**Comment by eoliveros** [comment]
made the entrypoint-shim executable. the container would fail to start otherwise.

**Pull request merged**
