### PR TITLE
Start on https://github.com/zap-me/ops/issues/169

### PR DESCRIPTION
**Pull request by 4855062503**
- Have set up a task for rebalancing which emails ADMIN once done

Currently stuck on why plugin `rebalance.py` is not being ran by `LnRpc`. 

Have read through Docker volumes documentation and tried running `lightning-cli` in `lightningd` container, to see if I could add the plugin flag, to no avail.

A bit stuck here on how to get the rpc to recognize `rebalance.py`

### CODE REVIEW

**Comment by djpnewton** [comment]
in the mean time you can make a task for `send_email`. And give it a better title

**Comment by 4855062503** [comment]
@djpnewton 
As in wrap this in another `task_manager` task?
```py
    email_utils.send_email(logger, 'Channel Rebalance Successful', 'Rebalanced {0} -> {1} with {2} sats'.format(oscid, iscid, amount))
```

**Comment by djpnewton** [comment]
make `send_mail` in *general* use a task

**Comment by djpnewton** [comment]
you should make `email_utils.py:send_email()` make a task internally so that any caller will automatically get the goodness:

something like:

```python
def _send_email_task():
    if not recipient:
        recipient = app.config["ADMIN_EMAIL"]
    assert recipient # shouldnt need this because of the above statement setting recipient, but oh well
    if app.config["USE_SENDGRID"]:
        return send_email_sendgrid(logger, subject, msg, recipient, attachment)
    return send_email_postfix(logger, subject, msg, recipient, attachment)

def send_email(logger: Logger, subject: str, msg: str, recipient: str | None = None, attachment: str | None = None) -> bool:
    task_manager.one_off_task('asdfskfjskljfg')
```

**Comment by djpnewton** [comment]
if/when ready to review flag Erick & I with the review request button

Also you should squash your commits

**Comment by 4855062503** [comment]
Think I screwed up my git rebase

**Pull request closed without merging**
